sonar.projectKey=ClinicaSonrisaPerfecta_G8
sonar.projectName=Sistema de Gestion Clinica Sonrisa Perfecta
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.language=py
sonar.python.version=3
sonar.sourceEncoding=UTF-8
